apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins-app
        image: watertechsakei/jenkins-python-docker:v2
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "100m"
        ports:
        - containerPort: 8080
