// pipeline {
//     agent any

//     environment {
//         IMAGE_NAME = 'watertechsakei/jenkins-flask-app'
//         IMAGE_TAG = "${IMAGE_NAME}:${env.GIT_COMMIT}"
        
//     }

    
//     stages {

//         stage('Setup') {
//             steps {
//                 sh "pip install -r requirements.txt"
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh "pytest"
//             }
//         }

//         stage('Login to docker hub') {
//             steps {
//                 withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
//                 sh 'echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin'}
//                 echo 'Login successfully'
//             }
//         }

//         stage('Build Docker Image')
//         {
//             steps
//             {
//                 sh 'docker build -t ${IMAGE_TAG} .'
//                 echo "Docker image build successfully"
//                 sh 'docker image ls'
                
//             }
//         }

//         stage('Push Docker Image')
//         {
//             steps
//             {
//                 sh 'docker push ${IMAGE_TAG}'
//                 echo "Docker image push successfully"
//             }
//         }      
//     }
// }

pipeline {
    agent any

    environment {
        IMAGE_NAME = 'watertechsakei/jenkins-flask-app'
        IMAGE_TAG = "${IMAGE_NAME}:${env.GIT_COMMIT}"
    }

    stages {
        stage('Setup') {
            steps {
                sh '''
                    
                    bash -c "
                        ls
                        cd 04-docker
                        python3 -m venv venv
                        source venv/bin/activate
                        pip install --upgrade pip
                        
                        pip install -r requirements.txt
                    "
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    
                    bash -c "
                        ls
                        cd 04-docker
                        source venv/bin/activate
                        pytest
                    "
                '''
            }
        }

        stage('Login to docker hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin'
                    echo 'Login successfully'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'ls'
                sh '''
                    bash -c "
                        cd 04-docker
                    "
                '''
                sh 'ls'
                sh 'docker build -t ${IMAGE_TAG} .'
                echo "Docker image build successfully"
                sh 'docker image ls'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push ${IMAGE_TAG}'
                echo "Docker image push successfully"
            }
        }
    }
}
